### ISSUE TITLE
Fix the mess docker-compose has made of it's dependencies

### ISSUE THREAD

**Issue by Fizzadar** [EDITD/kubetools#26]
`pip install kubetools` basically won't work because `docker-compose` seems to have extremely specific version dependencies for `requests`.

Perhaps instead of dealing with the mess they've made of things we can remove the dependency from this project (perhaps leave as an extra requirement).

**Comment by gchazot** [comment]
I'm tempted to reopen and revert.

This the first time I see a case where the new pip resolver has actually **fixed** things...
i.e. a straight revert of #36 now installs _cleanly_ (omitting the part where it downloads 20 versions of `docker-compose` before finding a compatible one)

**Comment by Fizzadar** [comment]
Was looking into this - Docker have recently(ish?) bundled compose with both Mac+Windows desktop versions, and there's also Linux packages. It seems that installing via pip is now not recommended (https://docs.docker.com/compose/install/).

**Comment by gchazot** [comment]
Fair enough. Their instructions to install on Linux are gonna mess people's Python venvs though.

There's a package for Ubuntu but even that installs a mass of python packages in the system interpreter.
That's not the right solution for everyone...

Maybe just worth a mention in the README to explain the situation

**Comment by Fizzadar** [comment]
Argh yeah that's v.frustrating! 👍 for readme addition for this. Have added https://github.com/EDITD/kubetools/issues/84 to track!
