### ISSUE TITLE
resolve port conflicts in containers

### ISSUE THREAD

**Issue by maapxa** [EDITD/kubetools#7]
There are cases when the `_create_compose_service` method allocates the same port to different containers. An example is with `data-curator-ec7733a2PR595-webserver` and `data-curator-ec7733a2PR595-redis` that are both allocated port 17821

**Comment by maapxa** [comment]
kudos to @risktoparkrageram for discovering this :tada:

**Comment by Fizzadar** [comment]
So these are [generated here](https://github.com/EDITD/kubetools-client/blob/develop/kubetools_client/dev/config.py#L145) - essentially we need a (better/new) way of turning a string into a consistent port between 1024-65536 without causing clashes (or, as few as possible).

**Comment by chrissinclairedited** [comment]
Other places that dynamically pick ports tend to check if the port is free, and if not then increment by 1 until they find a free port. We could probably do something similar here? Would probably mean that readme's couldn't rely on a specific port number though.

**Comment by Fizzadar** [comment]
I do not believe this is still an issue? Certainly not seen any recurrence in a long while...
