### ISSUE TITLE
Unable to pass flags to exec command

### ISSUE THREAD

**Issue by chrissinclairedited** [EDITD/kubetools#8]
When running `ktd exec`, it's not possible to pass flags to the command being run:

```
ktd exec local pytest -m interesting
```
should run `pytest -m interesting` within the local container, but instead produces this error:

```
▶ ktd exec local pytest -m i
Usage: ktd exec [OPTIONS] CONTAINER COMMAND...
Try "ktd exec --help" for help.

Error: no such option: -m
```

```
▶ ktd --version
ktd: v9.0.3
```

**Comment by Fizzadar** [comment]
Ah yes this is annoying; you have to use `--` for click to separate the arguments; eg:

```
ktd exec local -- pytest -m i
```

That should work!

**Comment by chrissinclairedited** [comment]
Ah can't believe I didn't try that! Thanks @Fizzadar!
