### ISSUE TITLE
Add non-blocking job creation in kubetools

### ISSUE THREAD

**Issue by marie-ll** [EDITD/kubetools#87]
Currently create_job function in kubernetes api waits for job to have succeeded.

For longer running jobs (like crawls) it would be useful to have a creation option that does not block the caller for duration of job. I am not familiar with the status transitions here but ideally it would wait for job to be 'started' for some definition of started.

**Comment by eatoncns** [comment]
Until I can edit description :)

Currently `create_job` function in kubernetes api waits for job to have succeeded.

For longer running jobs (like crawls) it would be useful to have a creation option that does not block the caller for duration of job. I am not familiar with the status transitions here but ideally it would wait for job to be 'started' for some definition of started.
